// frameworks/stencil/src/components/wc-button/wc-button.tsx
import { Component, Listen, Prop, h } from "@stencil/core";

@Component({
	tag: "wc-button",
	shadow: true,
})
export class WcButton {
	@Prop() variation: "primary" | "secondary" = "primary";

	@Listen("click")
	handleClick() {
		console.log(this.variation);
	}

	render() {
		return (
			<button
				style={{
					backgroundColor:
						this.variation === "secondary" ? "lightcoral" : "lightblue",
				}}
			>
				<slot></slot>
			</button>
		);
	}
}

// web-component/benchmarks/preact/src/components/Button.tsx
export type ButtonProps = {
	children: string;
	onClick: () => void;
	variation?: "primary" | "secondary";
};

export const Button = ({
	children,
	onClick,
	variation = "primary",
}: ButtonProps) => {
	return (
		<button
			style={{
				backgroundColor: variation === "secondary" ? "lightcoral" : "lightblue",
			}}
			onClick={onClick}
		>
			{children}
		</button>
	);
};
